name: E2E Cross-version Tests

on: [push]

jobs:

  source:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    services:
      metabase-source:
        image: metabase/metabase:v0.42.0
        ports:
          - "4200:3000"
        volumes:
          - $PWD/my-metabase:/metabase.db
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - run: ls $PWD
    - name: Wait for Metabase to start on port 4200
      run: while ! curl -s 'http://localhost:4200/api/health' | grep '{"status":"ok"}'; do sleep 1; done
    - name: Upload Metabase app DB
      uses: actions/upload-artifact@v2
      with:
        name: metabase-app-db
        path: $PWD/my-metabase/metabase.db.mv.db

  # target:
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 60
  #   needs: source
  #   services:
  #     metabase-target:
  #       image: metabase/metabase:v0.43.0
  #       ports:
  #         - "4300:3000"
  #       volumes:
  #         - /foobar/my-metabase:/metabase.db
  #       credentials:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   steps:
  #   - name: Download previously populated Metabase app DB
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: metabase-app-db
  #       path: /foobar/my-metabase/
  #   - name: Wait for Metabase to start on port 4300
  #     run: while ! curl -s 'http://localhost:4300/api/health' | grep '{"status":"ok"}'; do sleep 1; done
  #   - name: Bar
  #     run: ls /foobar/my-metabase/ | grep 'metabase.db'
