name: E2E Cross-version Tests

on: [push]

jobs:

  upgrade:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        source: [v0.42.0]
        target: [v0.43.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare front-end environment
      uses: ./.github/actions/prepare-frontend
    - name: Start Metabase ${{ matrix.source }}
      run: docker run -d -v $PWD/my-metabase:/metabase.db -p 3000:3000 --name metabase-${{ matrix.source }} metabase/metabase:${{ matrix.source }}
    - name: Wait for Metabase to start on port 3000
      run: while ! curl -s 'http://localhost:3000/api/health' | grep '{"status":"ok"}'; do sleep 1; done
    - name: Prepare cypress environment
      uses: ./.github/actions/prepare-cypress
    - name: Run Cypress
      run: |
        yarn cypress run \
          --browser chrome \
          --config-file frontend/test/metabase/scenarios/cross-version/source/cypress.json \
          --spec frontend/test/metabase/scenarios/cross-version/source/${{ matrix.source }}/setup.cy.spec.js
    - name: Stop Metabase ${{ matrix.source }}
      run: docker stop metabase-${{ matrix.source }}

    - name: Start Metabase ${{ matrix.target }}
      run: docker run -d -v $PWD/my-metabase:/metabase.db -p 3001:3000 --name metabase-${{ matrix.target }} metabase/metabase:${{ matrix.target }}
    - name: Wait for Metabase to start on port 3001
      run: while ! curl -s 'http://localhost:3001/api/health' | grep '{"status":"ok"}'; do sleep 1; done
    - run: ls ./my-metabase | grep 'metabase.db'
