name: E2E Cross-version Tests

on:
  push:


jobs:

  source:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    services:
      maildev:
        image: metabase/metabase:v0.42.0
        ports:
          - "4200:3000"
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Wait for Metabase to start on port 4200
      run: while ! curl -s localhost:4200/api/health; do sleep 1; done
    - name: Foo
      run: echo 'foo'

  target:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    needs: source
    services:
      maildev:
        image: metabase/metabase:v0.43.0
        ports:
          - "4300:3000"
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Wait for Metabase to start on port 4300
      run: while ! curl -s localhost:4300/api/health; do sleep 1; done
    - name: Bar
      run: echo 'bar'
